# Generated by Django 3.2.4 on 2021-07-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorUseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_numbr', models.CharField(max_length=4, unique=True)),
                ('password', models.CharField(max_length=4, unique=True)),
                ('fee', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
