# Generated by Django 3.2.5 on 2021-07-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_rename_room_numbr_dooruselog_door_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dooruselog',
            table='door_use_log',
        ),
    ]
